language: bash

os:
  - linux

services:
  - docker

branches:
  only:
    - master

script:
  - docker pull devkitpro/devkita64:latest
  - |
    docker run \
      -t \
      -v $(pwd):/repo \
      devkitpro/devkita64:latest \
      /bin/bash -c " \
        cd /repo \
        && make"

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: "output/release/diablo-nx.nro"
  skip_cleanup: true
  on:
    tags: true
